name: finalproject_pmoif20c_alif
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  another_flushbar: ^1.10.28
  awesome_dialog: ^2.1.2
  bloc: ^8.0.2
  cloud_firestore: ^3.1.8
  connectivity_plus: ^2.2.0
  date_picker_timeline: ^1.2.3
  day_night_time_picker: ^1.0.5
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  sizer: ^2.0.15
  awesome_notifications: ^0.6.21
  google_sign_in: ^5.2.4
  device_preview: ^1.0.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  firebase_storage: ^8.0.3
  file_picker: ^3.0.1


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
